#!/usr/bin/env python
# 
# suvat is an application that uses the equations of constantly accelerated
# motion to solve the motion of a particle. Its only external dependency 
# (apart from Python) is PyGTK/GTK.
#
# Copyright (C) 2009 Josh Holland
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Main script for suvat."""

from suvatlib import suvatwin
suvatwin.main()
